import Navbar from '../components/Navbar'
import Whatsapp from '../components/Whatsapp/Whatsapp'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Venus Delivery',
  description: 'Generated by create next app',
}

export default function BaseLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='h-full w-full'>
      <main className="flex h-full w-full flex-col items-center">
        <Navbar />
        {children}
        <Whatsapp/>
      </main>
    </div>
  )
}
